backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pageData/contact.md"
        label: "Contact Information"
        name: "contactInfo"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "contactInfo" }
          - { label: "Facebook URL", name: "facebookUrl", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
      - file: "src/pageData/header.md"
        label: "Header"
        name: "header"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "header" }
          - { label: "Logo image", name: "logoImage", widget: "image" }
      - file: "src/pageData/index.md"
        label: "Landing Page"
        name: "landing-page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "landing-page" }
          - { label: "Hero image", name: "heroImage", widget: "image" }
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Sub-headline", name: "subHeadline", widget: "string" }
          - { label: "Intro", name: "intro", widget: "markdown" }
      - file: "src/pageData/registration.md"
        label: "Volunteer Registration"
        name: "registration"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "registration" }
          - { label: "Pre-registration message", name: "preRegistrationMessage", widget: "markdown" }
          - { label: "Post-registration message", name: "postRegistrationMessage", widget: "markdown" }
