backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pageData/header.md"
        label: "Header"
        name: "header"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "header" }
          - { label: "Logo image", name: "logoImage", widget: "image" }
      - file: "src/pageData/index.md"
        label: "Landing Page"
        name: "landing-page"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "landing-page" }
          - { label: "Hero image", name: "heroImage", widget: "image" }
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Sub-headline", name: "subHeadline", widget: "string" }
          - { label: "Intro", name: "intro", widget: "markdown" }
